all: q1 q2 q3

q1:
	gcc 1/main.c 1/my_dll.c 1/my_dll.h 1/node.c 1/node.h -o q1.out

q2:
	gcc 2/main.c 2/complex.c 2/complex.h -lm -o q2.out

q3:
	gcc 3/main.c 3/song.c 3/song.h 3/musicplayer.c 3/musicplayer.h 3/user.c 3/user.h -o q3.out